# Generated by Django 6.0.6 on 2026-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('education', models.CharField(blank=True, max_length=250)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('height', models.CharField(blank=True, max_length=50)),
                ('complexion', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=250)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('native_place', models.CharField(blank=True, max_length=250)),
                ('father_name', models.CharField(blank=True, max_length=250)),
                ('mother_name', models.CharField(blank=True, max_length=250)),
                ('father_occupation', models.CharField(blank=True, max_length=250)),
                ('caste', models.CharField(default='Matang', max_length=100)),
                ('sub_caste', models.CharField(blank=True, max_length=100)),
                ('gotra', models.CharField(blank=True, max_length=100)),
                ('expectations', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('mr', 'Marathi'), ('en', 'English')], default='mr', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
