# Generated by Django 6.0.6 on 2026-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_email_member_updated_at_alter_member_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='brothers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='relative_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sisters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
